import type { Metadata } from "next";
import "./globals.css";
import { Questrial } from "next/font/google";
import { cn } from "@/lib/utils";
import Link from "next/link";
import Locale from "./_components/locale";

const q = Questrial({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Contentful Evaluation",
  description: "Generated by create next app",
};

const menus = [
  { id: 1, name: "Home", href: "/" },
  // { id: 2, name: "Evaluation", href: "/evaluation" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={cn(q.variable, "font-sans antialiased")}>
        <header className="bg-primary p-6 text-primary-foreground">
          <div className="container flex items-center justify-between">
            <div className="flex gap-x-4 lg:px-10 xl:px-20">
              {menus.map((menu) => (
                <Link
                  href={menu.href}
                  key={menu.href}
                  className="font-semibold"
                >
                  {menu.name}
                </Link>
              ))}
            </div>
            <div className="flex gap-x-4 lg:px-10 xl:px-20">
              <Locale />
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
