import type { Metadata } from "next";
import "./globals.css";
import { Questrial } from "next/font/google";
import { cn } from "@/lib/utils";

const questrial = Questrial({weight: ["400"], subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Contentful Evaluation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={cn(questrial.variable, "font-sans antialiased")}>
        {children}
      </body>
    </html>
  );
}
